# Generated by Django 3.2.6 on 2024-04-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASR1', '0002_auto_20240316_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
