# Generated by Django 3.2.6 on 2024-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASR1', '0003_auto_20240411_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privateKey', models.TextField()),
                ('publicKey', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='firma',
            field=models.TextField(default='firma'),
            preserve_default=False,
        ),
    ]
