"""
Django settings for BancoAlpes project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iv@^^7+_kf&0l#(o^n$3#82@rgd1#*4la4i#pf3hbodn5d$efj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ASR1',
    'ASR2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BancoAlpes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'BancoAlpes', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BancoAlpes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'banco_alpes_db',
        'USER': 'banco_alpes',
        'PASSWORD': 'banco_alpes',
        'HOST': '10.128.0.52',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static', 'ASR1'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Vonage API Credentials

VONAGE_API_KEY = 'd88431c3'
VONAGE_API_SECRET = 'zupVMm5EOR2SpYmY'


# Google Cloud Platform Credentials

PROJECT_ID="arquisoft-202410"
PRIVATE_KEY_ID="494c19cadd8b6211b303c8833377774e2d6818a4"
PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCjwiShJFvGrMwo\nkU4rLOtgjQJQFbdpXtcSH+HwtQJMDh9dhD0UWmwHDa9/PgQTcxP8eHbeIpDR8/L3\nF2bRNMnVWrhNjCe+A57QQ/lE5rAv4Mwy5frkQAgOitlI5uSZfqYHjU5qwzBz5Tfz\nYWYh/1ZgwAZqymiN6rRk6KqhsUKiQgKwm6ym1tpGcpZL4yuOORLs9id4TXQFNfK4\nMI6REz/8SbcfJ99kmvl/Sg1tS3BbNi54gwIbIzBs4o6vN1smAKkQcsT9Wr9+6JVI\nmEBommBfuXaelBFJdP6ya0yho26OWD7JJT2j92OAxEaa5qkkI1WgR3QpvmX6tlJU\ns0RD3ztHAgMBAAECggEAROrGuZ5wlVtRjF0ilZ8Q7BBMAeIxz0Gfp7wNPV0gO1vS\nLWwivHcVcZ571kQGOR08MwuLkw7e/cz52q1Zkv/xVT4ZxGEQtLIXWzTQKgQf7/Ze\nWalZ/kdIXL5olXq+iC65twHsF5hPwuabtmyuK+6mro8B5F2MxPUauEEG1oegMGKF\nII1JsngzyRLU3YZAt3oT+c58cUikftP3yAsfdiXfPV6fqo9ghyIgnRji6HeCzCeJ\nm4O9v1QhspT+Owp7+SfBehoFjxbP1SQx3oIQxar1sWdy1OJc1UebIxAJKz4QIz8U\nqmnBax5hfAlr/rxSE8FxMUN2JGlikw/YHsuHCFhe4QKBgQDOxL0N4MhEcV5Kdo2Z\nfvk7s5MA/Mf9DI9DxCX9DfAjZ/HDYF6zmX9RD8ivuKQa6b0V7os7V9aeBnTgDnE4\ntDH1+gQzjQSgDKFT88zaqCnaCvjTtxB6gUuOstc/mPLierYd2khX2Pojm7ibQ4om\ndedO01JNwpjQxwK70B953ho2VwKBgQDKv8lmWiX0UWlylNMyYsJbRHcmcpBMcBy7\ne8mszE+3VPWx9rn+nUcnky4EDypX3nAMYR2bPXd2bXUlewS4pSzWqBhYAvdR2ySw\nmodn8dbq7F5b5VcdC7XbdM4krAca8qTZWPyMypeNmQBFYTc1dwpVIc4psvlMudQG\np3FdvxyskQKBgQCt3+V3MSpX29nF1nH2vT7LBJQ/BVMLqa8j9mNXrIveyj8U5Apf\nD1pwCUzi7+sYMqxuL/3ndlMk6hsIezycyXMl/QvhadmU2Wok1eTTjww6rnVWXCBA\nVE/8fMnjUjQVXcmdyvyA2xZmMUIJVr9q3kUYFT6l41lsX54d38NIUQxL2wKBgQC2\nPcWuNoG/Jh5+W7+qnpLMrrHa4UdLLcrlytLwe4V76OYf3QI6Fu0KaYUHKQqKiOp2\ndiTCkXF8Bc8yrW0E+5NeLyISmjfsX+qOw5fKmtrvtx7pwy+WcBw68rcIx4hrdIcw\nxofblY68PDa+JjAV4rZq50QEv1bO3In0oTWJams/wQKBgBi0sAvRhcpihLKBxNt8\nuphsI8eaj9WnhYNCmuv3nn72XpStgqDjS9AZ8+jc8IxfPg/gdR5U8KOG4g4TKkq8\nx+k+wiyJljGx5ZjqyPfj0tVE5xJilMligxOC/1YhJ2jX0yevByvTeywx3chi3jFe\nCWFycN58/1SVi6mGYvosCKKb\n-----END PRIVATE KEY-----\n"
CLIENT_EMAIL="749913748910-compute@developer.gserviceaccount.com"
CLIENT_ID="109309646867057779574"